/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unisa.team8se.gui;

import it.unisa.team8se.DatabaseContext;
import it.unisa.team8se.Message;
import it.unisa.team8se.UserSession;
import java.awt.EventQueue;
import java.awt.Toolkit;
import java.sql.SQLException;

/**
 *
 * @author prgne
 */
public class LoginForm extends javax.swing.JFrame {

    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        utenteLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        ruoloLabel = new javax.swing.JLabel();
        roleSelector = new javax.swing.JComboBox<>();
        loginButton = new javax.swing.JButton();
        loginMessageLabel = new javax.swing.JLabel();
        viewPasswordButton = new javax.swing.JToggleButton();

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("Errore");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(Message.getImageIcon());
        setMaximumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        main.setBackground(new java.awt.Color(255, 198, 139));
        java.awt.GridBagLayout mainLayout = new java.awt.GridBagLayout();
        mainLayout.columnWidths = new int[] {0, 6, 0, 6, 0};
        mainLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        main.setLayout(mainLayout);

        loginLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("LOGIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 100;
        main.add(loginLabel, gridBagConstraints);

        utenteLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        utenteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        utenteLabel.setText("UTENTE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 10;
        main.add(utenteLabel, gridBagConstraints);

        usernameField.setText("Paco");
        usernameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 200;
        main.add(usernameField, gridBagConstraints);

        passwordLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordLabel.setText("PASSWORD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipady = 10;
        main.add(passwordLabel, gridBagConstraints);

        passwordField.setText("nothing");
        passwordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 200;
        main.add(passwordField, gridBagConstraints);

        ruoloLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        ruoloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ruoloLabel.setText("RUOLO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.ipady = 10;
        main.add(ruoloLabel, gridBagConstraints);

        roleSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Planner", "Maintainer" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        main.add(roleSelector, gridBagConstraints);

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 20;
        main.add(loginButton, gridBagConstraints);

        loginMessageLabel.setForeground(new java.awt.Color(204, 0, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        main.add(loginMessageLabel, gridBagConstraints);

        viewPasswordButton.setForeground(new java.awt.Color(255, 255, 255));
        viewPasswordButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unisa/team8se/assets/icons/eye.png"))); // NOI18N
        viewPasswordButton.setContentAreaFilled(false);
        viewPasswordButton.setPreferredSize(new java.awt.Dimension(30, 25));
        viewPasswordButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewPasswordButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                viewPasswordButtonMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        main.add(viewPasswordButton, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void raiseError(String message) {
        loginMessageLabel.setText(message);
        Toolkit.getDefaultToolkit().beep();
        clean();
    }

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        try {
            String user = usernameField.getText();
            String pwd = passwordField.getText();
            String role = (String) roleSelector.getSelectedItem();

            if (role.equals("Maintainer")) {
                if (UserSession.authenticateAsMaintainer(user, pwd)) {
                    EventQueue.invokeLater(() -> {
                        new MaintainerForm().setVisible(true);
                        dispose();
                    });
                    return;
                }
            } else if (role.equals("Planner")) {
                if (UserSession.authenticateAsPlanner(user, pwd)) {
                    EventQueue.invokeLater(() -> {
                        new PlannerForm().setVisible(true);
                        dispose();
                    });
                    return;
                }
            } else if (role.equals("Administrator")) {
                if (UserSession.authenticateAsSystemAdmin(user, pwd)) {
                    EventQueue.invokeLater(() -> {
                        new SystemAdminForm().setVisible(true);
                        dispose();
                    });
                    return;
                }
            }

            raiseError("USER O PASSWORD ERRATI");
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
            raiseError("ERRORE DI LOGIN");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        DatabaseContext.closeConnection();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void clean() {
        usernameField.setText("");
        passwordField.setText("");
    }

    private void usernameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameFieldMouseClicked
        usernameField.selectAll();
    }//GEN-LAST:event_usernameFieldMouseClicked

    private void passwordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFieldMouseClicked
        passwordField.selectAll();
    }//GEN-LAST:event_passwordFieldMouseClicked

    private void viewPasswordButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPasswordButtonMousePressed
        passwordField.setEchoChar((char)0);
    }//GEN-LAST:event_viewPasswordButtonMousePressed

    private void viewPasswordButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPasswordButtonMouseReleased
        passwordField.setEchoChar('*');
    }//GEN-LAST:event_viewPasswordButtonMouseReleased

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginForm lf = new LoginForm();
                lf.setVisible(true);
            }
        });

        //CONNESSIONE AL DB
        DatabaseContext.connectDatabase();
        //out.println(Activity.getInstanceWithWeekNumber(32));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel loginMessageLabel;
    private javax.swing.JPanel main;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JComboBox<String> roleSelector;
    private javax.swing.JLabel ruoloLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel utenteLabel;
    private javax.swing.JToggleButton viewPasswordButton;
    // End of variables declaration//GEN-END:variables
}
