/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unisa.team8se.gui;

import it.unisa.team8se.Activity;
import it.unisa.team8se.Area;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.LinkedList;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author cptso
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form ActivityList
     */

    class ActivityTableDataModel extends AbstractTableModel {

        @Override
        public String getColumnName(int column) {
            switch (column) {
                case 0:
                    return "ID";
                case 1:
                    return "AREA";
                case 2:
                    return "TYPOLOGY";
                case 3:
                    return "E.I.T.";
                default:
                    return "";
            }
        }

        @Override
        public int getRowCount() {
            return activities.size(); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public int getColumnCount() {
            return 4; //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {

            switch (columnIndex) {
                case 0:
                    return activities.get(rowIndex).getID();
                case 1:
                    return activities.get(rowIndex).getArea();
                case 2:
                    return activities.get(rowIndex).getTipology();
                case 3:
                    return activities.get(rowIndex).getEIT();
                default:
                    return null;
            }
        }
    }

    public MainForm() {
        initComponents();

        activities = new LinkedList<Activity>();

        Activity a0 = new Activity();
        a0.setID(0);
        a0.setTipology("Hydraulic");
        a0.setArea(new Area("fisciano", "plumbing"));
        a0.setEIT(120);
        Activity a1 = new Activity();
        a1.setID(1);
        a1.setTipology("Hydraulic");
        a1.setArea(new Area("fisciano", "plumbing"));
        a1.setEIT(90);
        Activity a2 = new Activity();
        a2.setID(2);
        a2.setTipology("Hydraulic");
        a2.setArea(new Area("fisciano", "plumbing"));
        a2.setEIT(100);
        Activity a3 = new Activity();
        a3.setID(3);
        a3.setTipology("Hydraulic");
        a3.setArea(new Area("fisciano", "plumbing"));
        a3.setEIT(122);

        activities.add(a0);
        activities.add(a1);
        activities.add(a2);
        activities.add(a3);

        layout = new CardLayout();
        layout.addLayoutComponent(activityList, "activityList");
        layout.addLayoutComponent(activitySummary, "activitySummary");

        setupActivityTable();

        container.setLayout(layout);
    }
    
    private void setupActivityTable(){
        activityTable.setModel(new ActivityTableDataModel());
        ListSelectionModel selectionModel = activityTable.getSelectionModel();
        selectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        selectionModel.setValueIsAdjusting(false);
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int selectedRow = activityTable.getSelectedRow();
                System.out.println("Selected index " + selectedRow);
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        activitySummary = new javax.swing.JPanel();
        activitySummaryLabel = new javax.swing.JLabel();
        activityList = new javax.swing.JPanel();
        activityListLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        activityTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        activitySummaryLabel.setText("ACTIVITYSUMMARY");

        javax.swing.GroupLayout activitySummaryLayout = new javax.swing.GroupLayout(activitySummary);
        activitySummary.setLayout(activitySummaryLayout);
        activitySummaryLayout.setHorizontalGroup(
            activitySummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activitySummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activitySummaryLabel)
                .addContainerGap(675, Short.MAX_VALUE))
        );
        activitySummaryLayout.setVerticalGroup(
            activitySummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activitySummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activitySummaryLabel)
                .addContainerGap(553, Short.MAX_VALUE))
        );

        activityListLabel.setText("ACTIVITYLIST");

        activityTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        activityTable.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(activityTable);

        javax.swing.GroupLayout activityListLayout = new javax.swing.GroupLayout(activityList);
        activityList.setLayout(activityListLayout);
        activityListLayout.setHorizontalGroup(
            activityListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activityListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(activityListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(activityListLayout.createSequentialGroup()
                        .addComponent(activityListLabel)
                        .addGap(0, 693, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE))
                .addContainerGap())
        );
        activityListLayout.setVerticalGroup(
            activityListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activityListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activityListLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(containerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(activitySummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(activityList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(containerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(activitySummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(activityList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        MainForm mf = new MainForm();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mf.setVisible(true);
                mf.layout.show(mf.container, "activityList");
            }
        });
        /*
        try {
            mf.layout.show(mf.container, "activityList");
            Thread.sleep(3000);
            mf.layout.show(mf.container, "activitySummary");
        } catch (InterruptedException e) {
        }
         */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel activityList;
    private javax.swing.JLabel activityListLabel;
    private javax.swing.JPanel activitySummary;
    private javax.swing.JLabel activitySummaryLabel;
    private javax.swing.JTable activityTable;
    private javax.swing.JPanel container;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private CardLayout layout;
    private LinkedList<Activity> activities;
}
